version: '3'
services:
  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9102}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9103}:9090'
    environment:
      MINIO_ROOT_USER: 'mps3'
      MINIO_ROOT_PASSWORD: 'ZOAmumEzdsUUcVlQ'
    command: minio server /data/minio --console-address ":9090"